---
title: "Modeling the Relationship of Gentrification and Crime"
author: "Matt Lehman"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
  html_document:
    fig_height: 4
    theme: yeti
    highlight: pygments
    toc: true
    toc_depth: 3
    toc_float: true
---

# Packages and Setup
```{r}
knitr::opts_chunk$set(dpi=1000,dev="bmp")
```

```{r}
library(rstan)
library(dplyr)
library(sf)
library(ggthemes)
library(ggplot2)
```


```{r}
theme_set(
  ggthemes::theme_tufte() +
    theme(panel.border = element_rect(color = "black", fill = NA))
)
```


```{r rstan setup}
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```


# Read and Munge Data
```{r read data}
la_neighborhood_incident_count <- readRDS("data/la_neighborhood_incident_count.RDS") %>% 
  mutate(city = "Los Angeles")

philly_neighborhood_incident_count <- readRDS("data/philly_neighborhood_incident_count.RDS") %>% 
  mutate(city = "Philadelphia")

pitt_neighborhood_incident_count <- readRDS("data/pitt_neighborhood_incident_count.RDS") %>% 
  mutate(city = "Pittsburgh")

sf_neighborhood_incident_count <- readRDS("data/sf_neighborhood_incident_count.RDS") %>% 
  mutate(city = "San Francisco")

neighborhood_gentrification <- readRDS("data/neighborhood_gentrification.RDS")
neighborhood_gentrification <- neighborhood_gentrification %>% 
  select(city, neighborhood, year, total_pop, gentrifiable, gentrifiable_prior, gentrifying)
```

Matching gentrification to incident data. 

```{r join data}
xl <- la_neighborhood_incident_count %>% 
  rbind(philly_neighborhood_incident_count) %>% 
  rbind(pitt_neighborhood_incident_count) %>% 
  rbind(sf_neighborhood_incident_count)

xl$geometry <- NULL

ggplot(xl, aes(x = incident_year, y = count, group = neighborhood)) +
  geom_point() +
  geom_line() +
  facet_wrap(~city)
# format incident data
data <- la_neighborhood_incident_count %>% 
  bind_rows(philly_neighborhood_incident_count) %>% 
  bind_rows(pitt_neighborhood_incident_count) %>% 
  bind_rows(sf_neighborhood_incident_count) %>% 
  group_by(city, neighborhood) %>% 
  mutate(count_next = lead(count, order_by = incident_year)) %>%
  filter(incident_year == 2012 | incident_year == 2017) %>%
  ungroup() %>% 
  inner_join(neighborhood_gentrification, by = c("city" = "city",
                                                 "neighborhood" = "neighborhood",
                                                 "incident_year" = "year")) %>% 
  group_by(city, neighborhood) %>% 
  mutate(
    rate = 1000 * count / total_pop # rate x 1k
    ,rate_next = 1000 * count_next / total_pop
    ,pct_change = (count_next - count) / count
  ) %>% 
  ungroup()
  
# remove geometry
data$geometry <- NULL

# prep for modeling
data <- data %>%  
  filter(gentrifiable_prior) %>% 
  mutate_at(vars(city, incident_year, gentrifiable, gentrifying), as.factor) %>% 
  # mutate_at(vars(rate, rate_next), log) %>% 
  # rename_at(vars(rate, rate_next), ~paste0(., "_log")) %>% 
  filter(complete.cases(.)) %>% 
  identity()


ggplot(data, aes(x = pct_change)) +
  geom_density(aes(fill = city, group = city), alpha = 0.4)

# ggplot(data, aes(x = rate_next_log)) +
#   geom_density(aes(fill = city, group = city), alpha = 0.4)
# 
# ggplot(data, aes(x = rate_log)) +
#   geom_density(aes(fill = city, group = city), alpha = 0.4)

# X <- model.matrix(rate_next_log ~ rate_log + city + incident_year + gentrifying, data)
X <- model.matrix(pct_change ~ city + incident_year + gentrifying, data)
lm <- lm(pct_change ~ city + incident_year + gentrifying, data)
summary(lm)

stan_dat <- list(
  N = nrow(X)
  ,y = data$pct_change
  ,K = ncol(X)
  ,pos = grep("gentrifying", colnames(X))
  ,X = X
)
```

# Modeling!
```{r}
fit <- stan(file = "model.stan", data = stan_dat, )
```

```{r}
library(broom)
pos <- grep("gentrifying", colnames(X))
param_sampled <- as_tibble(as.vector(as.matrix(fit)[ ,pos]))

greens <- RColorBrewer::brewer.pal(5, "Greens")
ggplot(param_sampled, aes(x = value, y = 1, fill=0.5 - abs(0.5-..ecdf..))) +
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE) +
  scale_fill_viridis_c(name = "Probability", direction = -1, breaks = c(0, 0.2, .4)) +
  labs(
    title = "Estimated Effect of Gentrification on Crime Incidents"
    ,x = "Percent Change in Incident Rate per 1K people in neighborhood"
    ,y = "Density"
  ) +
  scale_y_continuous(labels = NULL) +
  scale_x_continuous(labels = scales::percent) +
  mattle24utils::theme_mattle24() +
  NULL
 
# sum(param_sampled$value < 0) / length(param_sampled$value)
# sum(param_sampled$value > 0) / length(param_sampled$value)

fit_broom <- fit %>%
  tidy(conf.int = TRUE, conf.level = 0.95, conf.method = "quantile") %>% 
  mutate(
    term = c(colnames(X), "sigma")
  ) 

fit_broom

ggplot(fit_broom[-c(1, 12), ], aes(x = term, y = estimate)) +
  #geom_vline(xintercept = 0, color = "gray68", size = 3)+
  geom_linerange(aes(ymin = conf.low, ymax = conf.high), size = 3,
                 alpha = .6, color = "gold") +
  geom_point(size = 3) +
  labs(
    y = "Estimate (log incidents per 1K)"
    ,caption = "Bars represent 95% credible interval"
  ) +
  coord_flip() +
  NULL

# plot(fit)
# stan_dens(fit, pars = "beta[8]")
# stan_trace(fit)
```

```{r}

```

